site_name: GT_PKB
theme: 
  name: 'material'
  palette:
    scheme: slate
    primary: blue grey
    accent: pink
  features:
    - navigation.footer
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search
  - tags:
      tags_file: tags.md  

