site_name: GT_PKB
theme: 
  name: 'material'
  palette:
    scheme: slate
    primary: purple
    accent: light green
  features:
    - navigation.footer
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog:
      blog_toc: true

